### ISSUE TITLE
-maxVAFValid?

### ISSUE THREAD

**Issue by detorrentel** [viq854/lichee#6]
Hi,

I don't really understand why you put this option. Why are you filtering SSNVs where at least one sample has a VAF>0.6? I cannot find any explanations in the paper and I also looked at the supplementary about the datasets and you didn't put anything about filtering VAF>0.6. Maybe I missed it?

Thank you,
Laurence

**Comment by viq854** [comment]
The VAF of the root node (max expected VAF) is set to 0.5 in the network, since a VAF of 0.5 implies that the SSNV is present in 100% of the cells, with the assumption that the SSNVs are heterozygous. Of course many sources of error are possible (in addition to the effects of LOH, CNVs etc) and as a result mutations can have higher VAFs. The user can control what VAFs should be tolerated. Switching to CP values (if available) will mediate many such issues. The default of 0.6 comes from the default error margin of 0.1 (added on top of the 0.5).

**Comment by detorrentel** [comment]
Ok thank you, I think it would remove too much in my case. I estimated the purity of my sample using ABSOLUTE so I think I will use this value+0.1 for the maxVAFvalid.

Thank you so much for you answers, it's helping a lot!
